### ISSUE TITLE
Hinzufügen einer Öffnungszeit stellt ALLE Sonderzeiten auf "geöffnet" 

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#123]
![](https://i.imgur.com/5zfyl7h.png)
Es sollte nur der bearbeitete Eintrag geändert werden.

**Comment by jun71github** [comment]
Vorher:
![Screenshot1](https://user-images.githubusercontent.com/71936375/102716497-8b2aac00-42dc-11eb-866a-a6d98b4b1ef0.png)
Nachher:
![Screenshot2](https://user-images.githubusercontent.com/71936375/102716498-9251ba00-42dc-11eb-8159-9942acb6f590.png)
Scheint aber nur ein Anzeigeproblem zu sein:
![Screenshot3](https://user-images.githubusercontent.com/71936375/102716509-9e3d7c00-42dc-11eb-96cf-75ebc810486e.png)
