### ISSUE TITLE
Nach einer Simulation verschwindet die ausgewählte Upload-Datei aus dem Auswahlfeld für den Import

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#128]
...so dass sie neu ausgewählt werden muss, bevor der Import durchgeführt werden kann.
![image](https://user-images.githubusercontent.com/76115904/102720475-e23c7b00-42f4-11eb-8dc7-1b25c1f0ea47.png)
Für eine weitere Simulation ist das wünschenswert, für einen nachfolgenden Import erhöht dies wieder die Fehlerwahrscheinlichkeit.

Nachdem simuliert wurde, sollte (so wie es vorher auch gewesen ist) dieselbe Datei, die für das Simulieren verwendet worden ist, bereits vorausgewählt für den IMPORT zur Verfügung stehen.

Für eine weitere Simulation, ist das jetzige Verhalten richtig. 
Falls eine Fallunterscheidung da jetzt sehr aufwändig sein sollte, würde ich lieber den technischen Fehler bei der doppelten Simulation in Kauf nehmen wollen.

**Comment by marartz** [comment]
@jun71github : Das Issue kann im Branch develop getestet werden.
