### ISSUE TITLE
Bei der Neuanlage eines Restaurants kann keine Restaurantnummer vergeben werden

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#129]
Wie ist das denn künftig mit der Restaurantnummer gedacht? Die Idee wäre ja, mit dem neuen Backend die Restauranttabelle in ihrer Gänze aufzugeben und nur noch im Falle von Massen-Neuanlagen zu verwenden.
Kann ich denn auch eine Neuanlage im Backend machen?
Dann aber wüsste ich nicht mehr, wo ich bei einer Restaurant-Neuanlage im Backend die Restaurantnummer vergeben kann, die ich wiederum brauchte um später eine Speisentabelle beim Import dem richtigen Gastronom zuzuordnen...

**Comment by marartz** [comment]
In den allgemeinen Einstellungen des Restaurants kann die Import-Id des Restaurants nun festgelegt werden. Es wird aktuell aber nicht geprüft, ob diese eindeutig ist... Also Vorsicht! :-)

**Comment by annebeckmann** [comment]
Ok, wir passen auf.
