### ISSUE TITLE
Filterauswahl Lieferung/Abholung bleibt nicht bestehen, wenn man bei der Restaurantauswahl den Back-Button benutzt

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#130]
Wenn man alle Restaurants anzeigen lässt, dann den Filter von Abholung auf Lieferung setzt und sich dann mehrere Restaurants angucken möchte, springt der Filter nach Betätigung des Back-Buttons immer wieder auf die Ausgangsstellung (Abholung) zurück. Das bleibt insbesondere am Handy meist unbemerkt, so dass es zur Irritation kommt, dass der Kunde vermeintlich davon ausgeht, dass der von ihm gewählte Gastronom liefern kann, obgleich das gar nicht der Fall ist.
Besser wäre, die Auswahl (z.B. Lieferung) würde erhalten bleiben. 

Das steht einer Inbetriebnahme des Backends aber nicht entgegen.

**Comment by marartz** [comment]
@jun71github : Das Feature kann in feature/GH-130 getestet werden... Wenn Du damit anfängst, sprich mich kurz an. Ich habe noch etwas den Code umstrukturiert...

**Comment by marartz** [comment]
Bitte im develop testen.
