### ISSUE TITLE
Passwort Zurücksetzen-Funktion funktioniert nicht

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#131]
Anmelden --> hier dein Passwort zurücksetzen:

Egal wie schnell man auf den zugeschickten Link klickt, er ist jedes Mal schon nicht mehr gültig:
![](https://i.imgur.com/veKzSHY.png)

**Comment by marartz** [comment]
Wie bereits per WhatsApp beschrieben, liegt das an dem Link, der auf www.gastromio.de zeigt und nicht auf das Testsystem. => Close
