### ISSUE TITLE
Fehlanzeigen im Backend beim Überschreiten bestimmter Feldlängen von Speisekartenfeldern

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#135]
Im Backend werden manchmal die Icons für "Bearbeiten, Löschen und Sortieren" nicht angezeigt, wenn bestimmte Feldlängen überschritten werden:
![](https://i.imgur.com/VBIymab.png)

Sie lassen sich auch mit dem Scrollbalken nicht einblenden.

Welche Vorgaben gibt es, die wir ggfls. Usern hinsichtlich der maximalen Feldlängen kommunizieren können?
Momentan praktizieren wir: 
Speisenname: Max 30 Zeichen (inkl. Leerzeichen)
Speisenbeschreibung max 200 Zeichen (inkl. Leerzeichen)
Varianten: max 20 Zeichen (inkl. Leerzeichen)
Ist das so korrekt?

**Comment by marartz** [comment]
@annebeckmann : Folgende Limitierungen gelten:
- Speisenname: Max. 40 Zeichen (inkl. Leerzeichen)
- Speisenbeschreibung: Max. 200 Zeichen (inkl. Leerzeichen)
- Varianten: Max. 40 Zeichen (inkl. Leerzeichen)

Ich habe die Anzeige in der Speisenverwaltung verändert, so dass auch lange Bezeichnungen ordentlich dargestellt werden sollten.

@jun71github : Meine Änderungen können im Branch feature/GH-135 getestet werden.

**Comment by jun71github** [comment]
Hi @marartz 
Hier sollten wir noch ein paar Änderungen vornehmen:
1. Wenn der Name der Variante zu lang ist, dann ist die Info in der Hinweismeldung, welches Feld betroffen ist, nicht eindeutig. 'name' wird auch für den Namen des Gerichts verwendet.
![Screenshot2](https://user-images.githubusercontent.com/71936375/104103995-918dc180-52a5-11eb-969b-62120152979c.png)
![Screenshot1](https://user-images.githubusercontent.com/71936375/104103998-92beee80-52a5-11eb-8457-6a5ec26e65b0.png)
2. Wenn ich für den Namens des Gerichts mehr als 40 Zeichen eingebe und speichere, dann zeigt das System zwar die Hinweimeldung an, schließe ich aber nun den Dialog, dann zeigt das System trotzdem den zu langen Namen in der Übersicht an.
![Screenshot3](https://user-images.githubusercontent.com/71936375/104104057-f8ab7600-52a5-11eb-9290-ed3b91c0d4ed.png)
Nach dem Neuladen der Seite steht wieder der "alte" Name drin, das System speichert ihn zwar nicht ist aber trotzdem für den Benutzer verwirrend. Das gilt auch für das Feld "Beschreibung des Gerichts"
3. 'description' könnte für den Benutzer nicht sofort klar sein, was gemeint ist
![Screenshot4](https://user-images.githubusercontent.com/71936375/104104121-740d2780-52a6-11eb-8918-6ecc49f360be.png)
4. 'producinfo' könnte für den Benutzer nicht sofort klar sein, was gemeint ist
![Screenshot5](https://user-images.githubusercontent.com/71936375/104104149-969f4080-52a6-11eb-9bc7-06c119fb8895.png)

**Comment by marartz** [comment]
Die Änderungen sind jetzt im develop testbar.

**Comment by jun71github** [comment]
@marartz:
Ein Hinweistext ist noch nicht OK, der Rest passt nun.
![Screenshot1](https://user-images.githubusercontent.com/71936375/104237908-12d98580-5459-11eb-9114-d9153e31dcea.png)

**Comment by marartz** [comment]
@jun71github : Habe ich angepasst... Und das Ticket auf Merged geschoben.
