### ISSUE TITLE
Verdeckte Anzeige der Telefonnummer des Restaurants

### ISSUE THREAD

**Issue by marartz** [marartz/Gastromio#136]
Um eine Analyse zu ermöglichen, wer über einen Telefonanruf bestellt, soll im Checkout-Dialog die Telefonnummer dies Restaurants erst verdeckt angezeigt werden. Erst wenn der Benutzer auf "Telefonnummer anzeigen" klickt, soll die Telefonnummer aufgedeckt werden.

**Comment by marartz** [comment]
@jun71github : Das Feature kann jetzt im Branch feature/GH-136 getestet werden.

**Comment by jun71github** [comment]
@marartz 
Das Feature funktioniert soweit, aber wenn der Benutzer nochmal auf das Feld (mit der aufgeklappten Telefonnummer) klickt, dann zeigt das System diesen Dialog an:
![Screenshot1](https://user-images.githubusercontent.com/71936375/104105733-71173480-52b0-11eb-89e3-688d03ea6166.png)

**Comment by marartz** [comment]
@jun71github : Das ist normal und sogar gewünscht. Wenn Du eine App auf dem PC bzw. insalliert hast bzw. auf dem Mobiltelefon öffnet sich die Telefon-App, um den Anruf direkt zu tätigen.

**Comment by marartz** [comment]
Feature ist jetzt in develop
