### ISSUE TITLE
Anzeige der Preise bei den Varianten fehlerhaft

### ISSUE THREAD

**Issue by jun71github** [marartz/Gastromio#142]
Wenn der Restaurantadmin ein Gericht bearbeitet, dabei verschiedene Varianten mit unterschiedlichen Preisen anlegt, dann zeigt das System immer den Preis der ersten Variante in der Übersicht an.
Fehler tritt nur im Feature Branch GH-135 auf. Im develop Branch ist es OK.
![Screenshot1](https://user-images.githubusercontent.com/71936375/104104888-00214e00-52ab-11eb-90a4-3efca116d1af.png)

**Comment by marartz** [comment]
Kann in develop getestet werden.
