### ISSUE TITLE
Selbstständige Änderung des Passworts

### ISSUE THREAD

**Issue by lucawieczorek** [marartz/Gastromio#143]
![Screenshot_2021-01-10 Gastromio – Essen lokal bestellen](https://user-images.githubusercontent.com/44336042/104136184-e1978180-5394-11eb-8709-2c605b9c19a9.png)
Der Restaurantadministrator soll sein eigenes Passwort ändern können.

**Comment by marartz** [comment]
@ikke09 : Du könntest Dich an diesem Feature versuche... Große Teile davon sind schon implementiert (siehe Branch feature/GH-143). Vielleicht kannst Du das finalisieren?

**Comment by ikke09** [comment]
@marartz Ich habe mal versucht mir einen Überblick zu verschaffen. Was bisher implementiert wurde und bereits funktioniert:

- [x] "Passwort ändern" Icon in der Top-Bar anzeigen
- [x] ChangePassword-Component im Frontend implementiert und Routing angepasst
- [x] Neuer API Entpunkt "changepassword" im Auth-Service implementiert. Funktionstüchtig für SysAdmin

ToDo:

- [ ] Funktion auch für Restaurant Admins ermöglichen
- [ ] (Design anpassen)

Offene Fragen:
* Die aktuelle Implementierung weicht vom Design auf @lucawieczorek Screenshot ab. Soll das noch geändert werden?
* SysAdmin können nun auf die selbe Funktionalität durch unterschiedliche Wege auslösen. Siehe Screenshot:
![grafik](https://user-images.githubusercontent.com/19330925/114318427-26a28f80-9b0d-11eb-9960-0b4b65e8dda6.png)
Soll dies vereinheitlicht werden?


Ich hoffe, dass ich soweit nichts übersehen habe. Bitte fehlende Punkte ergänzen 😄

**Comment by marartz** [comment]
@ikke09: Ich denke, Du hast den aktuellen Stand gut erfasst 👍 .

Idee ist, dass jeder authentifizierte Benutzer sein eigenes Passwort ändern kann. Daher würde ich folgendes vorschlagen:
Backend:
- Das Kommando ChangeUserPasswordCommand ist nur den SysAdmins vorbehalten und wird auch nur da aufgerufen (Route /users/{userId}/changepassword)
- Ein neues Kommando ChangeOwnPasswordCommand (inkl. Handler) erstellen, welches nur das Ändern des eigenen Passworts ermöglicht (Route /changepassword); dies kann dann für alle authentifizierten Benutzer freigegeben werden
Frontend:
- Ich würde von dem Design, welches @lucawieczorek vorgeschlagen hat, abweichen und die Funktionalität so bereitstellen, wie ich es bereits vorimplementiert habe

Reicht das als Info? Sonst können wir gerne auch nochmal telefonieren...

**Comment by ikke09** [comment]
Ich glaube, dass ich alles soweit umsetzen konnte. PR (#192) ist bereit zum Review. 🚀

**Comment by marartz** [comment]
@jun71github : Wie bereits erwähnt, kann das Feature in Branch feature/GH-143 getestet werden.
