### ISSUE TITLE
Darstellung der Bestellabwicklung

### ISSUE THREAD

**Issue by lucawieczorek** [marartz/Gastromio#144]
![Screenshot_2021-01-10 Gastromio – Essen lokal bestellen(1)](https://user-images.githubusercontent.com/44336042/104136236-2de2c180-5395-11eb-8c5e-d6703e67935a.png)
Bestellung von <select> zu <button>

Und Übergabe von <input> zu <button>

Branch design-revision

**Comment by marartz** [comment]
@lucawieczorek : Habe den Branch auf den letzten Stand von develop gebracht.

**Comment by marartz** [comment]
Ich habe das jetzt soweit umgesetzt. @lucawieczorek : Musst/willst Du hier nochmal darüber schauen oder darf @jun71github schon anfangen zu testen?

**Comment by marartz** [comment]
@jun71github : Testbar wäre das im Branch feature/design-revision

**Comment by jun71github** [comment]
Tested with branch "design-revision".
