### ISSUE TITLE
Bearbeitungsfunktionen im Backend unsichtbar im mobilen Modus und vertikaler Ansicht

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#146]
In der **Rolle Administrator** sind auf diversen Mobilgeräten z.B. Pixel 2 in der Hochformatnutzung die Bearbeitungicons nicht zu sehen. (wohl aber zu benutzen, wenn man weiß, dass sie da sind)

![image](https://user-images.githubusercontent.com/76115904/104454588-60173d80-55a6-11eb-9c73-dbd3468407f1.png)

in der horizontalen Ansicht sind sie dagegen problemlos sichtbar.

**Comment by jun71github** [comment]
Der Fehler ist leider nicht mit dem Ticket #150 behoben. Keine Änderung erkennbar.

**Comment by lucawieczorek** [comment]
Hast du auch im Branch #150 nachgeschaut?
LG

**Comment by jun71github** [comment]
Hi @lucawieczorek , ja ich habe das mit dem Branch #150 getestet.

**Comment by lucawieczorek** [comment]
Aber inwiefern siehtst du denn keine Änderungen? @jun71github

**Comment by jun71github** [comment]
@lucawieczorek 
die beiden Buttons "Vorschau" und "Bearbeiten" sind beide nicht vorhanden.
![grafik](https://user-images.githubusercontent.com/71936375/108412970-b83b0280-722a-11eb-8a53-5b536c1d8334.png)

**Comment by marartz** [comment]
@jun71github : Problem sollte jetzt gefixt sein.

**Comment by lucawieczorek** [comment]
@marartz Woran hat es gelegen? Das Design kommt mit auch überhaupt nicht bekannt vor ^^
