### ISSUE TITLE
Erkennbar machen, dass das Verwaltungsmenü außerhalb des Sichtbereiches weitergeht

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#148]
Es ist kaum erkennbar, dass die Menüzeile durch verschieben nach rechts erweitert werden kann. Hier könnten kleine weiße Dreieckspfeile erkennbar machen, dass das Menü rechts vom angezeigten Bereich noch weitergeht.
![image](https://user-images.githubusercontent.com/76115904/104455718-fbf57900-55a7-11eb-8760-78e73d59bedf.png)

Das gilt gleichermaßen auch in der horizontalen Ansicht.

**Comment by marartz** [comment]
@annebeckmann : Das Thema wird mit GH-162 gefixt.
