### ISSUE TITLE
Darstellung der Systemadministration

### ISSUE THREAD

**Issue by lucawieczorek** [marartz/Gastromio#150]
Auf der linken Seite (wie in der Restaurantadministration) die Navigationsleiste, auf der rechten Seite die einzelnen Unterseiten (Benutzer-, Restaurant, -verwaltung)

**Comment by marartz** [comment]
@lucawieczorek : Ich habe das basierend auf Deinem Redesign jetzt umgesetzt. Du müsstest Dir das bitte noch ordentlich anschauen und designtechnisch verbessern.

**Comment by jun71github** [comment]
Evtl. ist #146 auch hier mit gelöst.

**Comment by marartz** [comment]
Kann in Branch feature/GH-150 getestet werden.

**Comment by jun71github** [comment]
1. Bei jedem Eintragwechsel in der Navigationsleiste, zeigt das System "Änderungen wurden gespeichert", obwohl nicht sgeändert wurde
![Screenshot1](https://user-images.githubusercontent.com/71936375/107079482-368db280-67f0-11eb-8361-8776c4bf0746.png)
2. Im Menü "Restaurantimport" nach Klick auf "Simulieren", zeigt das System auch hier "Änderungen wurden gespeichert" an. Dies ist verwirrend für den Benutzer
![Screenshot2](https://user-images.githubusercontent.com/71936375/107079669-7785c700-67f0-11eb-9e91-08701a2c6a47.png)
3. Das Suchfeld im Menü "Benutzer" ist angerundet, dadurch ist der erste Buchstabe des Suchbegriffs abgeschnitten
![Screenshot3](https://user-images.githubusercontent.com/71936375/107079791-9f752a80-67f0-11eb-85c3-7f04574192f1.png)
4. Wenn ich die Suche im Menü "Benutzer" verwendet habe, das Menü wechsle und wieder zurück zum Menü "Benutzer" gehe, dann ist der "alte" Suchbegriff noch immer vorhanden. Ist das so gewollt?

**Comment by jun71github** [comment]
@lucawieczorek 
Hast du hier Änderungen gemacht? Der Branch feature/GH-150 hat keine Updates seit meinem letzten Test vor 13 Tagen.

**Comment by marartz** [comment]
@jun71github : Probleme sollten jetzt gefixt sein.
