### ISSUE TITLE
Öffnungszeiten: Mülleimersymbol löscht falschen Eintrag

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#158]
Wenn man zwei Öffnungszteiten pro Tag hat und zuerst die spätere Öffnungszeit eingibt und erst nachher die erste (z.B. erst 17-20:00 Uhr und danach erst 10-12:00 Uhr) dann tauschen sich die beiden Öffnungszeiten automatisch in der Backendansicht aus. Das ist schick. Aber leider tauschen die beiden Mülleimersymbole nicht mit. D.h. um 10-12:00 Uhr wieder zu löschen, muss man dann auf den Mülleimer hinter 17-20:00 Klicken....

**Comment by marartz** [comment]
@jun71github : Kann in Branch bugfix/GH-158 getestet werden.
