### ISSUE TITLE
AOS (Animate on Scroll) funktioniert nicht auf dem Testserver

### ISSUE THREAD

**Issue by lucawieczorek** [marartz/Gastromio#160]

**Comment by marartz** [comment]
@jun71github : Kann auf develop getestet werden.

**Comment by jun71github** [comment]
Hi @marartz, AOS klingt super :)
Kannst du mir kurz sagen, was das ist?
Ich vermute mal, wenn ich bis zum Ende einer Seite scrolle, dass das System diesen Bereich
![grafik](https://user-images.githubusercontent.com/71936375/110020245-a462c680-7d29-11eb-8092-f90ba4ec48c2.png)
animiert anzeigt.

**Comment by marartz** [comment]
@jun71github : Das kannst Du tatsächlich einfach durchschieben. Das ist ein rein technisches Problem.
