### ISSUE TITLE
Link zum Frontend aus dem Backend eines Gastronoms

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#161]
Den Link zum Frontend finde ich gut,
![image](https://user-images.githubusercontent.com/76115904/109387640-d8da1b00-7902-11eb-92b4-8beddbfb13d4.png)
allerdings noch sinnvoller wäre er INNERHALB des Restaurants, denn man benutzt ihn, wenn man was geändert hat, z.B. die Speisekarte. Dann hat man das Bedürfnis zum Frontend zu wechseln, um es sich anzusehen. (Um nur das Frontend eines Wirtes zu besuchen, würde ich ja nicht erst ins Backend wechseln)

z.B. Hier könnte man den Link zum Frontend sinnvoll einbauen, idealerweise in einem neuen Tab, denn oft will man danach ins Backend zurück und noch etwas ändern. Das sollte also offen bleiben.
![image](https://user-images.githubusercontent.com/76115904/109387753-851c0180-7903-11eb-8d97-217325f6967c.png)

**Comment by marartz** [comment]
Kann in Branch feature/GH-161 getestet werden.

**Comment by marartz** [comment]
@jun71github : Ab jetzt im develop-Branch.
