### ISSUE TITLE
Menü in der mobilen Ansicht (Pixel2) teilweise nicht vollsändig

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#162]
Die obere Menüzeile wird bei kleineren Mobilgeräten nicht angezeigt. Entweder Menüzeile umbrechen oder mit < und > Scrollen zulassen.
![image](https://user-images.githubusercontent.com/76115904/109387999-ca8cfe80-7904-11eb-90fe-ae967832c4aa.png)

Das gilt gleichermaßen auch für die Menüzeile INNERHALB eines Restaurants:
![image](https://user-images.githubusercontent.com/76115904/109388060-13dd4e00-7905-11eb-9254-80453e4ec85f.png)

**Comment by marartz** [comment]
@jun71github : Kann im Branch feature/GH-162 getestet werden.

**Comment by marartz** [comment]
@jun71github : Ab jetzt im develop-Branch.

**Comment by jun71github** [comment]
Es funktioniert soweit, aber wenn ich z.B. den Menüpunkt "Restaurantimport" aufrufe, dann verschwindet der Menüpunkt direkt wieder aus dem sichtbaren Bereich.
Ich vermute mal, dass es daran liegt, dass das System nach klicken auf einen Menüpunkt auch das Menü neu lädt.
In der Restaurantverwaltung passiert das nicht.

**Comment by jun71github** [comment]
Es bleibt erstmal so wie es ist.
