### ISSUE TITLE
Wie kommt das Essen zum Kunden ergänzen um "Reservierung"

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#163]
Am 27.2. gab es nun auch die erste politische Verlautbarung, dass der Lockdown "möglichst bald, auf jeden Fall vor Ostern" für die Außengastronomie aufgehoben werden könnte. Daher sollten wir im Backend neben
- Abholung und
- Lieferung
- Reservierung
vorsehen

Alter Vorschlag:
![image](https://user-images.githubusercontent.com/76115904/109388373-f4dfbb80-7906-11eb-85a0-37b6544c78ac.png)

**Comment by marartz** [comment]
@jun71github : Ab jetzt im develop-Branch.
