### ISSUE TITLE
Auswahlknöpfe der Bestellabwicklung (umtexten oder als Mehrfachauswahl hinterlegen)

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#169]
Die Knöpfe für die Bestellabwicklung müssten entweder mit Mehrfachauswahl funktionieren, oder aber anders beschriftet werden. 
![image](https://user-images.githubusercontent.com/76115904/110239669-61cb0500-7f48-11eb-9685-fb438f4327b4.png)
1. Telefonisch
2. Telefonsich & Online-Vorbestellung
3. Telefonisch & Online-Vorbestellung & Online-Bestellung während der Öffnungszeiten

Mit Mehrfachauswahl (So wie bei Abholung, Lieferung, Tischreservierung) ist es natürlich super chick...

**Comment by jun71github** [comment]
1. In der drittten Option ist nicht der komplette Text enthalten. Derrot marierte Bereich fehlt
![Screenshot1](https://user-images.githubusercontent.com/71936375/111221239-82dfc580-85da-11eb-9c8f-79bd33c6183e.jpeg)
2. In der Restaurantübersicht fehlt der erweiterte Text
![Screenshot2](https://user-images.githubusercontent.com/71936375/111221552-f08bf180-85da-11eb-9d22-6926af180aae.png)

**Comment by marartz** [comment]
@jun71github : Den zweiten Punkt habe ich gefixt... "... während der Öffnungszeiten" habe ich weggelassen...
