### ISSUE TITLE
Speisenkategorien einschalten/ausschalten

### ISSUE THREAD

**Issue by marartz** [marartz/Gastromio#171]
Als Restaurantadministrator möchte ich in der Speisekartenverwaltung einzelne Speisenkategorien einschalten und ausschalten können.

Wenn eine Kategorie ausgeschaltet ist, sollen die Speisen dieser Kategorie sowie die Kategorie selbst in der Bestellansicht nicht mehr zu sehen sein.

**Comment by jun71github** [comment]
Hi @marartz, in welchem Branch kann ich das testen?
