### ISSUE TITLE
Texte der Reservierungsbestätigungen per Mail beziehen sich auf Bestellungen

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#177]
Statt Bestellung müsste da sinngemäß Reservierung stehen. 
Oder falls man dasselbe Formular benutzen möchte kann man m.E. ruhig auch von Bestellung/Reservierung sprechen.

![image](https://user-images.githubusercontent.com/76115904/111082902-12b63e80-850b-11eb-940f-ffae5fab9765.png)

![image](https://user-images.githubusercontent.com/76115904/111083064-d6cfa900-850b-11eb-9907-3c8e306ed4c6.png)

**Comment by jun71github** [comment]
@marartz 
Der neue Text ist nun drin, soweit OK.
Aber habe noch einen kleinen Änderungswunsch bzgl. der gelb markierten Stelle.
![Screenshot3](https://user-images.githubusercontent.com/71936375/111369751-b7658700-8697-11eb-9836-35d25954364a.png)

**Comment by marartz** [comment]
@jun71github : Habe ich gefixt...
