### ISSUE TITLE
Übergabeauswahl fehlt in der Restaurantauswahl

### ISSUE THREAD

**Issue by jun71github** [marartz/Gastromio#179]
Wenn der Benutzer auf der Startseite den Button „Alle anzeigen“ verwendet, dann zeigt das System in der Restaurantauswahl die Übergabeauswahl nicht an.
![Screenshot1](https://user-images.githubusercontent.com/71936375/111367074-9f403880-8694-11eb-878e-dd6420b26e05.png)
Nach dem Neuladen der Seite ist es OK.

**Comment by marartz** [comment]
@jun71github : Gefixt in develop
