### ISSUE TITLE
Reservierungs-Button-Zusatz "(ab 22.03.)" ersetzen durch "(gem. CSV)"

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#180]
Aufgrund der unerwartet stark in die Höhe geschnellten Infektionszahlen ist der Termin 22.3. leider obsolet geworden. 
Ich schlage vor wir ersetzen das durch "(gem. CSV)"

![image](https://user-images.githubusercontent.com/76115904/111800230-0ac01b00-88cc-11eb-8a26-42e0a4508ae9.png)

Und hier auch: Statt ab 22.3. --> "sofern offiziell gestattet"
![image](https://user-images.githubusercontent.com/76115904/111800842-a3569b00-88cc-11eb-846d-06232fa5a748.png)

**Comment by jun71github** [comment]
@marartz: Kann es ein, dass es den Branch GH-180 nicht (mehr) gibt? Bekomme jedefalls einen Fehler, wenn ich versuche ihn zu pullen.

**Comment by marartz** [comment]
@jun71github : Ja, das Feature ist schon nach develop gegangen...

**Comment by jun71github** [comment]
@marartz: Da scheint wohl etwas schief gelaufen zu sein. Im Develop Branch ist nicht mal der "alte" Text vorhanden.
![Screenshot1](https://user-images.githubusercontent.com/71936375/114927051-587b6500-9e31-11eb-9f59-9d71fb0f74f9.png)
![Screenshot3](https://user-images.githubusercontent.com/71936375/114927063-5addbf00-9e31-11eb-9a8d-9ecb054a012f.png)

**Comment by marartz** [comment]
@jun71github : Habe das Problem in develop gefixt.
