### ISSUE TITLE
Sortierung der Speisen innerhalb einer Kategorie fehlerhaft

### ISSUE THREAD

**Issue by lucawieczorek** [marartz/Gastromio#182]
<img width="917" alt="Bildschirmfoto 2021-03-26 um 20 07 31" src="https://user-images.githubusercontent.com/44336042/112681467-13d25e80-8e6f-11eb-8100-0f1c8d26dcfb.png">
<img width="1024" alt="Bildschirmfoto 2021-03-26 um 20 07 11" src="https://user-images.githubusercontent.com/44336042/112681472-15038b80-8e6f-11eb-9ea6-11ff2450b0d8.png">

**Comment by marartz** [comment]
@lucawieczorek , @jun71github 👍 

Das ist tatsächlich reproduzierbar, wenn man folgendes macht:

1. Restaurant im "Front-End" (Bestellsystem) öffnen
2. Im "Back-End" (Admin-Bereich) Sortierung anpassen
3. Restaurant im "Front-End" aufmachen (ohne die Seite neu zu laden)

Sobald die Seite neu lädt, ist die Sortierung korrekt...

**Comment by marartz** [comment]
@jun71github : Testbar in "develop".

**Comment by jun71github** [comment]
Schaut OK aus. Hatte aber auch keine "alte" Version, wo ich den Fehler exakt reproduzieren kann.

**Comment by lucawieczorek** [comment]
@marartz Ist das Issue schon live?

**Comment by lucawieczorek** [comment]
> @marartz Ist das Issue schon live?

@marartz Einmal kurzes Update bitte

**Comment by marartz** [comment]
Nein, das ist noch nicht live.

**Comment by lucawieczorek** [comment]
> Nein, das ist noch nicht live.

Okay, alles klar.
