### ISSUE TITLE
Git Clone Fehler auf Windows

### ISSUE THREAD

**Issue by ikke09** [marartz/Gastromio#185]
Hey Leute,
unter Windows kann ich das Repo nicht klonen. Beim Ausführen von git clone bekomme ich folgende Fehlermeldung:

```
error: invalid path 'src/Gastromio.App/ClientApp/src/assets/fonts/apercu/apercu-black-italic-pro.eot?#iefix'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```

Für Windows haben die Dateien leider einen invaliden Dateinamen und können nicht gespeichert werden.
Als Workaround kann ich in einem Branch alle *.eot?#iefix direkt auf Github löschen und dann direkt diesen speziellen Branch klonen. Build und Run funktionieren weiterhin.

Wozu dienen diese Dateien? Könnten diese umbenannt werden, damit die auch auf Windows genutzt werden können?

Danke und schöne Grüße,
Christian

**Comment by marartz** [comment]
@ikke09 : Vielen Dank fürs Melden! @lucawieczorek : Ich meine, dass wir bereits kurz über das Thema gesprochen haben. Können die Dateien entfernt werden?

**Comment by lucawieczorek** [comment]
@marartz Ganz genau - Können einfach entfernt werden.

**Comment by marartz** [comment]
@ikke09 : Möchtest Du einen Pull Request (PR) erstellen, oder soll ich das die Dateien entfernen?

**Comment by ikke09** [comment]
@marartz Ich habe die Änderung in meinem Fork bereits gemacht. Werde mal versuchen ein PR von dort zu erstellen.
