### ISSUE TITLE
Backend Menüstruktur bricht nicht um

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#188]
Bei Überschreiten einer bestimmten Zahl Menü-Unterteilungen, bricht die Anzeige im Backend nicht mehr korrekt um. Im folgenden Beispiel gibt es eine weitere Kategorie, die gar nicht mehr angezeigt wird und auch durch Scrollen nicht sichtbar gemacht werden kann.

![image](https://user-images.githubusercontent.com/76115904/113170088-8748e700-9246-11eb-9c1c-c84db58c77c5.png)

**Comment by lucawieczorek** [comment]
Verweise auf Ticket #193
