### ISSUE TITLE
Erweiterung der max. Länge der Speisenbeschreibung 

### ISSUE THREAD

**Issue by marartz** [marartz/Gastromio#194]
**Story:**
Als Restaurantadministrator möchte ich für Speisen mehr als die aktuell möglichen 200 Zeichen eingeben können, damit ich die vollständige Beschreibung meiner Speise angeben kann.

**Akzeptanzkriterien:**:
- Die Restaurantadministration ermöglicht eine Beschreibung von 500 Zeichen anzugeben
- Im Bestellsystem müssen solch langen Beschreibungen einer Speise in der Desktop- und auch in der mobilen Ansicht ordentlich dargestellt werden

**Comment by marartz** [comment]
@ikke09 : Das wäre vielleicht auch etwas für Dich? :-)

**Comment by ikke09** [comment]
@marartz Das kling recht simpel auf den ersten Blick, da mache ich mich mal ran 💪🏽

**Comment by ikke09** [comment]
> **Akzeptanzkriterien:**:
> 
>     * Die Restaurantadministration ermöglicht eine Beschreibung von 500 Zeichen anzugeben
> 
>     * Im Bestellsystem müssen solch langen Beschreibungen einer Speise in der Desktop- und auch in der mobilen Ansicht ordentlich dargestellt werden

@marartz 
* Soll die selbe Begrenzung für die ProduktInfos gelten?
* Sollte die Textbox gar nicht erst mehr Zeichen zulassen?
* Soll ein Indikator für die Zeichen angezeigt werden (Unterhalb der Textbox z.B. 30/500 Zeichen)?

**Comment by ikke09** [comment]
Hey,
Durch das Setzen der maximalen Zeichen bekomme ich leider ein weiteres UI-Problem.

![grafik](https://user-images.githubusercontent.com/19330925/115119021-a1085f00-9fa6-11eb-964e-69cd3b8b7380.png)

Der Text wird hier dann viel zu Breit für die Anzeige. Würde im Normalfall den Text mit "..." kürzen. Hier macht mir aber Issue #166 einen Strich durch die Rechnung, da sich der ganze Inhalt einfach nach rechts viel zu breit ausdehnt. Dieses Feature wird also durch #166 etwas blockiert.

**Comment by jun71github** [comment]
Wenn man viele Zeichen in dem Feld "Beschreibung des Gerichts" eingibt und speichert ist danach die Ansicht nicht mehr in Ordnung. Im Bereich "Speisekarte" fehlen die Icons und im Bereich "Externe Speisekarte" ist der Inhalt nun zu breit und dadurch die rechte Seite abgeschnitten.
![Screenshot1](https://user-images.githubusercontent.com/71936375/119718828-56f97f80-be68-11eb-9201-7e447e0c2037.png)

Im Bestellsystem wird nicht der komplette Text angezeigt und durch die Breite der Beschreibung fehlt der Preis.
![Screenshot2](https://user-images.githubusercontent.com/71936375/119720014-c3c14980-be69-11eb-845a-e8c145c0e88a.png)

Tested with Branch "feature_GH-194"

**Comment by ikke09** [comment]
@jun71github Ich glaube wir haben diesen Issue in der Vergangenheit etwas missbraucht. Deine Screenshots zeigen im Grunde einen Anzeigefehler. Dieser steht in Verbindung mit Issue #166.

In diesem Issue habe ich lediglich die maximale Zeichenanzahl begrenzt und diesen Zähler eingeführt. Meine Änderungen hierfür sind in #198 dokumentiert.

Ich habe die Anzeigefehler allerdings nun beheben/verbessern können und nutze dafür jetzt einfach mal Issue #166. Also dort geht es weiter und dieser Issue muss nicht mehr wiedergeöffnet werden 😉
