### ISSUE TITLE
Schaltfläche zum Anzeigen des Kennworts

### ISSUE THREAD

**Issue by jun71github** [marartz/Gastromio#199]
Wenn der Benutzer auf der Seite „localhost/changepassword“ in dem Feld „Passwort“ Zeichen eingibt, dann blendet das System das Augesymbol ein, soweit OK.
Springt der Benutzer nun danach in das Feld „Passwort wiederholen“, dann blendet das System nun das Augesymbol in dem zweiten Feld ein, auch soweit OK.
Springt der Benutzer nun zurück zum ersten Feld, dann ist auch das Augesymbol auch im zweiten Feld verschwunden. Dadurch hat der Benutzer nun keine Chance mehr die bisher eingegeben Zeichen in beiden Feldern zu checken.
Ich denke, das Augesymbol sollte immer sichtbar sein, sobald in dem Feld mindestens ein Zeichen vorhanden ist.

Identisches Problem auf der Seite „localhost/admin/users“, wenn der Systemadmin das Passwort von Benutzern ändert.

**Comment by lucawieczorek** [comment]
Fällt mit ins Redesign der Login- und Registrierseiten. Sieht Issue #25

**Comment by lucawieczorek** [comment]
🔎 To Be Tested in develop.
@jun71github

**Comment by lucawieczorek** [comment]
🔒️ Edge-Seitiges Feature, kein Bug.
