### ISSUE TITLE
Öffnungszeiten werden als überschneidend zurückgewiesen, obgleich sie nicht überschneiden

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#207]
![image](https://user-images.githubusercontent.com/76115904/118397985-e9bf4080-b656-11eb-8a0d-3ac616aab73b.png)

**Comment by marartz** [comment]
@annebeckmann : Für Gastromio statet ein Tag um 04:00 Uhr morgens und endet um 03:59 morgens des nächsten Kalendertags. Daher kannst Du einfach 18:00 - 02:30 angeben.
