### ISSUE TITLE
Redesign für die Grundauswahl Abholung/Lieferung/Tischreservierung

### ISSUE THREAD

**Issue by annebeckmann** [marartz/Gastromio#209]
Es sollte  Abholung & Tischreservierung vorausgewählt sein. Die Leute verstehen, dass sie zwischen Abholung und Lieferung wählen kann, aber Tischreservierung wird manchmal nicht erkannt. Das ist blöd für die Wirte, die NUR Tischreservierung haben, die werden schlecht gefunden.  

![image](https://user-images.githubusercontent.com/76115904/119058151-187a4580-b9ce-11eb-840e-eb1960e04ed9.png)

**Comment by lucawieczorek** [comment]
Aber werden dann die Gastronomiebetriebe, die keine Tischreservierung ausgewählt haben, nicht vernachlässigt bzw. schlechter gefunden? @annebeckmann

**Comment by lucawieczorek** [comment]
❌ Keine Reaktion auf das Issue.
Somit sehe ich das Issue für geschlossen.
