### ISSUE TITLE
Neue Fehler im develop Branch

### ISSUE THREAD

**Issue by jun71github** [marartz/Gastromio#215]
Siehe Anhang
[neue Bugs develop Branch.docx](https://github.com/marartz/Gastromio/files/6729147/neue.Bugs.develop.Branch.docx)

**Comment by lucawieczorek** [comment]
@jun71github ich kann Fehler 6 nicht reproduzieren...
Könntest du mir den näher erläutern?

**Comment by jun71github** [comment]
@lucawieczorek: Der Fehler scheint ein Folgefehler von 3 und 5 zu sein. Habe den Fehler eben gehabt. Der geht dann auch nicht mehr weg. Erst nach "Neustart". Die genauen STR´s habe ich (noch) nicht. Ich arbeite dran ;)

**Comment by lucawieczorek** [comment]
> @lucawieczorek: Der Fehler scheint ein Folgefehler von 3 und 5 zu sein. Habe den Fehler eben gehabt. Der geht dann auch nicht mehr weg. Erst nach "Neustart". Die genauen STR´s habe ich (noch) nicht. Ich arbeite dran ;)

Alles klar, werde ich mir die Tage dann mal in Ruhe anschauen.

**Comment by marartz** [comment]
@jun71github : Fehler Nr. 2 habe ich gefixt.

**Comment by lucawieczorek** [comment]
> @jun71github : Fehler Nr. 2 habe ich gefixt.

@marartz Könntest du dir bitte nochmal die Modals anschauen?

**Comment by marartz** [comment]
Fehler 3, 5, 7, 9 sollte gefixt sein.

**Comment by jun71github** [comment]
@marartz @lucawieczorek 
Die Fehler 3, 5, 7 und 9 sind gefixt.

**Comment by jun71github** [comment]
Aktueller Stand:
[neue Bugs develop Branch_2.docx](https://github.com/marartz/Gastromio/files/6743624/neue.Bugs.develop.Branch_2.docx)

**Comment by marartz** [comment]
Haben für die gefundenen Punkte einzelne Issues angelegt. Das Issue schließen wir jetzt.
