### ISSUE TITLE
Tippfehler in der Hilfe

### ISSUE THREAD

**Issue by marartz** [marartz/Gastromio#216]
Einige Tippfehler in der Hilfe (siehe Bild).

![image](https://user-images.githubusercontent.com/60776602/125346102-a08b2480-e359-11eb-9b38-281e5e274c8a.png)

![image](https://user-images.githubusercontent.com/60776602/125346171-b4cf2180-e359-11eb-87f5-31b264442e33.png)

![image](https://user-images.githubusercontent.com/60776602/125346192-b8fb3f00-e359-11eb-9dcb-a66b0676d44b.png)

**Comment by ikke09** [comment]
Hey @marartz & @lucawieczorek,
könnt Ihr mir sagen wie die Hilfe eingebunden ist? Sehe nur in den Dev-Tools, dass diese in einem iFrame leben, aber kann im Code diese Einbindung gar nicht finden. Weiß nicht wonach ich noch suchen kann 😅 Finde die Texte nicht in unserem Frontend-Code und kann diese entsprechend nicht anpassen...

**Comment by lucawieczorek** [comment]
> Hey @marartz & @lucawieczorek,
> 
> könnt Ihr mir sagen wie die Hilfe eingebunden ist? Sehe nur in den Dev-Tools, dass diese in einem iFrame leben, aber kann im Code diese Einbindung gar nicht finden. Weiß nicht wonach ich noch suchen kann 😅 Finde die Texte nicht in unserem Frontend-Code und kann diese entsprechend nicht anpassen...

Die Zugangsdaten schicke ich dir via WA.

**Comment by ikke09** [comment]
Tippfehler wurden direkt in Freshdesk angepasst, wodurch diese Änderungen direkt live sind. Schließe daher dieses Issue
