### ISSUE TITLE
Bestellung kann nicht abgesetzt werden

### ISSUE THREAD

**Issue by jun71github** [marartz/Gastromio#223]
Zur Zeit kann keine Bestellung abgesetzt werden. Das System zeigt immer diesen Fehler an:
![2021-08-10 22_17_55-](https://user-images.githubusercontent.com/71936375/128929464-ab000bb1-82f0-4c2a-974c-239d1c613cd4.png)

**Comment by ikke09** [comment]
@jun71github Funktionieren bei dir aktuell gar keine Bestellungen? Ich konnte eine Bestellprozess erfolgreich durchspielen und durchführen.

Könntest du diesen Prozess bitte nochmal machen und in den Dev-Tools den Output von "Checkout Model" und den Fehler aufklappen (kleies Dreieck links neber den Nachrichten). Dies entweder nochmal Screenshoten oder direkt hier rein kopieren. Dann könnten wir sehen, worüber sich das System beklagt. Danke dir ☺

**Comment by jun71github** [comment]
Hi @ikke09,
habe den Fehler gefunden bzw. kann ihn jetzt reproduzieren :)
Generell funktionieren jetzt auch bei mir Bestellungen. Ich hatte gestern immer das gleiche Gericht für Bestellungen verwendet. Daher sah es für mich so aus, dass gar keine Bestellungen funktionieren.
Der Fehler kommt zustande, da das verwendete Gericht sich in einer Kategorie befindet, welche nicht aktiv ist.
![grafik](https://user-images.githubusercontent.com/71936375/129102849-b666c103-22a3-453e-9b22-c1bef23ae8f1.png)
Rufe ich nun die Speisekarte des Restaurants auf, dann bietet mir das System trotzdem die deaktivierte Kategorie inkl. des Gerichts an.
![grafik](https://user-images.githubusercontent.com/71936375/129103096-b0dd53f3-a1a6-405f-9b91-cf56ba9bb46b.png)
Legt man nun dieses Gericht in den Warenkorb und geht zum "Checkout", dann kommt es zu dem oben beschriebenen Fehler.

**Comment by ikke09** [comment]
@jun71github Danke fürs Nachforschen. Dann schaue ich mir das ganze mal an und werde die inaktive Kategorie bei der Bestellung ausblenden, sowie eine Überprüfung einbauen, dass es nicht im Warenkorb landet
