### ISSUE TITLE
Sortierung der Speisen nicht möglich

### ISSUE THREAD

**Issue by jun71github** [marartz/Gastromio#228]
Wenn der Restaurantadmin auf der Seite „Speisekarte“ die Sortierung der Gerichte ändern will, dann erlaubt das System dies nicht und zeigt nur diese Fehlermeldung an:
![Screenshot1](https://user-images.githubusercontent.com/71936375/131882697-20d67a5b-69f9-4d62-be64-49e641feabe8.png)
STR´s
- Anmelden
- Restaurants
- Restaurant bearbeiten
- Speisekarte
- Beliebige Gerichtskategorie auswählen
- Pfeil „rauf“ oder „runter“ anklicken

**Comment by ikke09** [comment]
Konnte das Problem behebn. Dem Backend wurde die DishCategory nicht mehr übergeben, wodurch die Sortierung nicht durchgeführt werden konnte. PR #232 ist erstellt, wartet auf Merge
