### ISSUE TITLE
Tooltip nicht komplett lesbar

### ISSUE THREAD

**Issue by jun71github** [marartz/Gastromio#229]
Wenn der Restaurantadmin auf der Seite „Speisekarte“ mit der Maus über den Pfeil „runter“ fährt, dann zeigt das System den Tooltip nicht komplett an.
![Screenshot1](https://user-images.githubusercontent.com/71936375/131883692-c4e854c8-3613-44e9-a0ec-167d6456761b.png)

**Comment by ikke09** [comment]
Konnte es nicht ganz beheben, aber zu 90% würde ich sagen 😅
Habe den Text etwas verkürzt und die Scrollbar unterdrückt. Nicht optimal, aber man kann zumindest den Text vollständig lesen und das Flackern der Scrollbar iritiert nicht mehr.

![grafik](https://user-images.githubusercontent.com/19330925/133136478-22d7b499-982c-4bee-8f8d-fb69e7bef6cc.png)

**Comment by ikke09** [comment]
PR ist erstellt, wartet auf Merge 😎
