### ISSUE TITLE
SMS-Versand funktioniert nicht

### ISSUE THREAD

**Issue by jun71github** [marartz/Gastromio#234]
Wenn für ein Restaurant die Funktion „Automatischer SMS-Versand bei Bestelleingang“ aktiviert ist und ein Kunde eine Bestellung für dieses Restaurant aufgibt, dann erzeugt/versendet das System keine SMS.
Bei mir kommt zu mindestens nichts an.

**Comment by marartz** [comment]
@jun71github : Bei mir hat das ordentlich funktioniert... Lass uns mal schauen, wir genau Du die Konfiguration eingestellt hast...
