### ISSUE TITLE
Menüeinträge vom Adminmenü entkoppelt

### ISSUE THREAD

**Issue by jun71github** [marartz/Gastromio#51]
Wenn der Benutzer das Adminmenü öffnet, während das Menü geöffnet ist die "STRG"-Taste + Mausrad verwendet um den Zoomfaktor zu verändern, dann verändert das Menü zwar auch seine Größe ist aber von der Überschrift entkoppelt.
![Screenshot1](https://user-images.githubusercontent.com/71936375/97369158-a369e600-18ac-11eb-9c46-f8876e0a2d63.png)

**Comment by jun71github** [comment]
Das Menü ist nun nicht mehr von der Überschrift entkoppelt, aber:
1. Bei dem Eintrag "Abmelden" ändert sich der Mauszeiger nicht zur Hand. Das Abmelden funktioniert allerdings
![2021-01-24 21_35_59-Gastromio – Essen lokal bestellen - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/71936375/105671384-e7d44480-5ee2-11eb-96d5-dee11fa58d13.png)
2. Nach dem Anmelden ist das Menü weg
3. Beim Aufruf des Menüs, kommt das seitlich "reingefahren". Ist das Absicht?

**Comment by marartz** [comment]
@lucawieczorek : Kannst Du etwas zu Jürgens Frage oben sagen?

**Comment by lucawieczorek** [comment]
@marartz Der Dropdown ist entfernt. Jetzt muss nur noch ein Logout-Button in den System- sowie Restaurantadmin-Reiter implementiert werden. Branch #145

**Comment by marartz** [comment]
Branch ist design-revision

**Comment by jun71github** [comment]
Tested with branch "design-revision".
