### ISSUE TITLE
Warenkorb im Checkout

### ISSUE THREAD

**Issue by jun71github** [marartz/Gastromio#99]
Wenn der Benutzer im Checkout den Warenkorb anklickt, das Restaurent nur telefonische Bestellungen entgegen nimmt, dann zeigt das System die Speisekarte nicht an.
![Screenshot1](https://user-images.githubusercontent.com/71936375/100134199-20768400-2e88-11eb-90bd-d5b9dfd4532f.png)
![Screenshot2](https://user-images.githubusercontent.com/71936375/100134225-28cebf00-2e88-11eb-9abd-b8948aacddf3.png)

**Comment by marartz** [comment]
@jun71github : Ich glaube, das ist kein Bug... schau bitte nochmals nach.

**Comment by lucawieczorek** [comment]
Bitte hole dir den neusten Stand via Docker @jun71github
